language: node_js
node_js:
- '0.12'
env:
  global:
  - GH_REF=github.com/developmentseed/openroads-analytics.git
  - DEPLOY_BRANCH=master
  - secure: sYu3pAJ6P2Ckewb1Khb/KUk7cGemhEKIMqHTMqpC1xTaqP2Q1yZPtsASkamDScS1ZCSNoa0NnHZTA96dI9QsELoX1hPSaVU3JjmuLjhELxK9tWddHjzSgNyNPtVGSPgjNz7YlRgJs2ktPTO4N4qAOqEqe+xH4JFnaR/6VK6GGgU=

before_install:
  - chmod +x ./.build_scripts/build.sh
  - chmod +x ./.build_scripts/deploy.sh

after_success:
  - ./.build_scripts/build.sh
  - ./.build_scripts/deploy.sh
